name: textifier
version: 1.0.0
author: Volk <me@volk.pt>
description: Convert images to text in your browser
homepage: https://github.com/TemplarVolk/dart-textifier
environment:
  sdk: '>=2.0.0 <3.0.0'
